name: Tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * *"
  release:
    types:
      - published

defaults:
  run:
    shell: bash -l {0}

jobs:
  tests:
    runs-on: ${{ matrix.OS }}-latest
    name: tests
    strategy:
      matrix:
        os: ['ubuntu']
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: python -m pip install -e .
      - name: Install testing
        run: python -m pip install pytest pytest-cov
      - name: Versions
        run: python -m pip list
      - name: Run tests
        run: pytest -v --pyargs ticgithub --cov=ticgithub --cov-report xml
      - name: CodeCov
        uses: codecov/codecov-action@v3

